# Generated by Django 5.0.6 on 2024-07-09 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('status', models.CharField(max_length=50, verbose_name='status : pending , failled , succes')),
                ('order_id', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=50, verbose_name='type : retrait , depot')),
                ('operateur', models.CharField(max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entreprise')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcation', to='core.wallet')),
            ],
            options={
                'verbose_name': 'Transcation',
                'verbose_name_plural': 'Transcations',
            },
        ),
    ]
