# Generated by Django 5.0.6 on 2024-07-09 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_transcation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='categorie/')),
                ('date', models.DateField(verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('diplome', 'Diplôme'), ('certification', 'Certification'), ('autre', 'Autre')], max_length=50, verbose_name='type de document')),
                ('nom_document', models.CharField(max_length=255, verbose_name='nom du document')),
                ('fichier_document', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='fichier du document')),
                ('lien_document', models.URLField(blank=True, null=True, verbose_name='lien vers le document')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='nom de la réalisation')),
                ('description', models.TextField(verbose_name='description de la réalisation')),
                ('date', models.DateField(verbose_name='date')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realisations', to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='PieceJointeRealisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='realisations/', verbose_name='fichier')),
                ('lien', models.URLField(blank=True, null=True, verbose_name='lien')),
                ('realisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='folio.realisation')),
            ],
        ),
    ]
